# Generated by Django 3.2.24 on 2024-02-18 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_remove_emotion_criminal_emotion_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminallogs',
            name='time',
            field=models.TimeField(default='12:00'),
            preserve_default=False,
        ),
    ]
