# Generated by Django 3.2.24 on 2024-02-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_criminallogs_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialalert',
            old_name='distance',
            new_name='violations_count',
        ),
        migrations.AddField(
            model_name='socialalert',
            name='photo',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialalert',
            name='time',
            field=models.TimeField(default='11:30'),
            preserve_default=False,
        ),
    ]
